uncertain: occur some unknow problem
casdoor/casdoor-raw-js-example pull request #2
Opened 2022-10-09 10:25 UTC by kcfuler

2022-10-11 05:18 UTC, hsluoyz commented
@leo220yuyaodog plz review

2022-10-11 06:22 UTC, leo220yuyaodog commented
Now the demo has basicly implement the login process, but still has some shortcoming need to improve.
1. After login, show `logout` button and support logout. Now the demo can not logout, and do not keep the logged in state. I suggest that using `sessionStorage` to do it. 
2. Add some css make the page look nice. Like center the button and use table to show user information.

2022-10-11 06:33 UTC, leo220yuyaodog commented on src/web/index.html
> +    <label for="avatar">avatar</label><img id="avatar" />
Use table <tr>

2022-10-11 06:33 UTC, leo220yuyaodog commented on src/web/index.html
> +        // fetch('http://localhost:8080/api/userinfo').then(res => res.json()).then(userinfo => {
delete useless comment

2022-10-11 06:33 UTC, leo220yuyaodog commented on src/web/index.html
> +      if (window.location.href.indexOf('code') !== -1 && !window.location.href.includes('oauth')) {
why `&& !window.location.href.includes('oauth')`

2022-10-11 06:52 UTC, kcfuler commented
ok, i will do this soon

2022-10-12 02:14 UTC, leo220yuyaodog approved these changes

2022-10-15 02:20 UTC, hsluoyz requested changes

2022-10-15 02:20 UTC, hsluoyz commented on README.md
> +![](https://github.com/kcfuler/casdoor-vanilla-js-example/blob/master/gif/%E7%A4%BA%E4%BE%8B%E8%A7%86%E9%A2%911.gif?raw=true)
Use English file name

2022-10-15 02:22 UTC, merged